default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  port: 5432
  username: nathapotthaweepong
  password: 1234

development:
  <<: *default
  database: pos_app

test:
  <<: *default
  database: pos_app_test

production:
  <<: *default
  database: pos_app
